prueba/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login.in');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('logout', 'Auth\LoginController@logout');

/*
|--------------------------------------------------------------------------
| Seguridad rutas de la aplicación
|--------------------------------------------------------------------------
*/
Route::group(['middleware' => 'auth'], function()
{
    Route::get('/', 'HomeController@index')->name('home');

    /**
     * 1. Personas
     */
    Route::resource('persons', 'Seguridad\PersonaController');
    
    /**
     * 2. Áreas
     */
    Route::resource('areas', 'Core\AreaController');

    /**
     * 3. Países
     */
    Route::resource('countries', 'Core\PaisController');

    /**
     * 4. Departamentos
     */
    Route::resource('states', 'Core\DepartamentoController');

    /**
     * 5. Ciudades
     */
    Route::resource('cities', 'Core\CiudadController');

    /**
     * 6. Email
     */
    Route::resource('email', 'Core\EmailController');
});

prueba/resources/views/admin/shared/head.blade.php
<!-- Favicon icon -->
<link rel="icon" href="{{ asset('GradientAble/files/assets/images/favicon.ico') }}" type="image/x-icon">
<!-- Google font-->
<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600" rel="stylesheet">
<!-- Required Fremwork -->
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/bower_components/bootstrap/css/bootstrap.min.css') }}">
<!-- Syntax highlighter Prism css -->
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/assets/pages/prism/prism.css') }}">
<!-- sweet alert framework -->
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/bower_components/sweetalert/css/sweetalert.css') }}">
<!-- themify-icons line icon -->
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/assets/icon/themify-icons/themify-icons.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/assets/icon/simple-line-icons/css/simple-line-icons.css') }}">
<!-- ico font -->
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/assets/icon/icofont/css/icofont.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/assets/icon/typicons-icons/css/typicons.min.css') }}">
<!-- Font Awesome -->
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/assets/icon/font-awesome/css/font-awesome.min.css') }}">
<!-- animation nifty modal window effects css -->
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/assets/css/component.css') }}">
<!-- notify js Fremwork -->
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/bower_components/pnotify/css/pnotify.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/bower_components/pnotify/css/pnotify.brighttheme.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/bower_components/pnotify/css/pnotify.buttons.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/bower_components/pnotify/css/pnotify.history.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/bower_components/pnotify/css/pnotify.mobile.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/assets/pages/pnotify/notify.css') }}">
<!-- Data Table Css -->
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/bower_components/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/assets/pages/data-table/css/buttons.dataTables.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/assets/pages/data-table/extensions/responsive/css/responsive.dataTables.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/bower_components/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/assets/pages/data-table/extensions/buttons/css/buttons.dataTables.min.css') }}">
<!-- Select 2 css -->
<link rel="stylesheet" href="{{ asset('GradientAble/files/bower_components/select2/css/select2.min.css') }}" />
<!-- Style.css -->
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/assets/css/style.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/assets/css/jquery.mCustomScrollbar.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('GradientAble/files/assets/icon/flag-icons/css/flag-icon.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('css/global.css') }}">
@stack('styles')

prueba/resources/views/admin/shared/header.blade.php
<div class="pcoded-container navbar-wrapper">
    <nav class="navbar header-navbar pcoded-header">
        <div class="navbar-wrapper">
            <div class="navbar-logo">
                <a class="mobile-menu hover-menu" id="mobile-collapse" href="#!">
                    <i class="ti-menu"></i>
                </a>
            <div class="mobile-search">
                <div class="header-search">
                    <div class="main-search morphsearch-search">
                        <div class="input-group">
                            <span class="input-group-addon search-close"><i class="ti-close"></i></span>
                                <input type="text" class="form-control" placeholder="Enter Keyword">
                                    <span class="input-group-addon search-btn"><i class="ti-search"></i></span>
                        </div>
                    </div>
                </div>
            </div>
            <a href="{{ route('home') }}">
                <img class="img-fluid" src="{{ asset('GradientAble/files/assets/images/logo.png') }}"  alt="Theme-Logo" />
            </a>
            <a class="mobile-options">
                <i class="ti-more"></i>
            </a>
        </div>
        <div class="navbar-container container-fluid">
            <ul class="nav-right">
                <li class="header-notification">
                    <a>
                        <i class="ti-bell"></i>
                        <span class="badge bg-c-pink"></span>
                    </a>
                    <ul class="show-notification">
                    </ul>
                </li>
                <li class="user-profile header-notification">
                    <a>
                        <img src="{{ asset('GradientAble/files/assets/images/avatar-4.jpg') }}"  class="img-radius" alt="User-Profile-Image">
                        @if(Auth::check())
                            <span>{{ Auth::user()->name }}</span>
                            <i class="ti-angle-down"></i>
                        @endif
                    </a>
                    <ul class="show-notification profile-notification">
                        <li>
                            <a href="{{ url('/logout') }}">
                                <i class="ti-layout-sidebar-left"></i> Cerrar sesión
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

prueba/resources/views/admin/shared/scripts.blade.php
<!-- Required Jquery -->
<script  src="{{ asset('GradientAble/files/bower_components/jquery/js/jquery.min.js') }}"></script>
<script  src="{{ asset('GradientAble/files/bower_components/jquery-ui/js/jquery-ui.min.js') }}"></script>
<script  src="{{ asset('GradientAble/files/bower_components/popper.js/js/popper.min.js') }}"></script>
<script  src="{{ asset('GradientAble/files/bower_components/bootstrap/js/bootstrap.min.js') }}"></script>
<!-- jquery slimscroll js -->
<script  src="{{ asset('GradientAble/files/bower_components/jquery-slimscroll/js/jquery.slimscroll.js') }}"></script>
<!-- modernizr js -->
<script  src="{{ asset('GradientAble/files/bower_components/modernizr/js/modernizr.js') }}"></script>
<script  src="{{ asset('GradientAble/files/bower_components/modernizr/js/css-scrollbars.js') }}"></script>
<!-- Syntax highlighter prism js -->
<script  src="{{ asset('GradientAble/files/assets/pages/prism/custom-prism.js') }}"></script>
<!-- data-table js -->
<script src="{{ asset('GradientAble/files/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('GradientAble/files/bower_components/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('GradientAble/files/assets/pages/data-table/js/jszip.min.js') }}"></script>
<script src="{{ asset('GradientAble/files/assets/pages/data-table/js/pdfmake.min.js') }}"></script>
<script src="{{ asset('GradientAble/files/assets/pages/data-table/js/vfs_fonts.js') }}"></script>
<script src="{{ asset('GradientAble/files/bower_components/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('GradientAble/files/bower_components/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('GradientAble/files/bower_components/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('GradientAble/files/bower_components/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('GradientAble/files/bower_components/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js') }}"></script>
<!-- pnotify js -->
<script src="{{ asset('GradientAble/files/bower_components/pnotify/js/pnotify.js') }}"></script>
<script  src="{{ asset('GradientAble/files/bower_components/pnotify/js/pnotify.desktop.js') }}"></script>
<script  src="{{ asset('GradientAble/files/bower_components/pnotify/js/pnotify.buttons.js') }}"></script>
<script  src="{{ asset('GradientAble/files/bower_components/pnotify/js/pnotify.confirm.js') }}"></script>
<script  src="{{ asset('GradientAble/files/bower_components/pnotify/js/pnotify.callbacks.js') }}"></script>
<script  src="{{ asset('GradientAble/files/bower_components/pnotify/js/pnotify.animate.js') }}"></script>
<script  src="{{ asset('GradientAble/files/bower_components/pnotify/js/pnotify.history.js') }}"></script>
<script  src="{{ asset('GradientAble/files/bower_components/pnotify/js/pnotify.mobile.js') }}"></script>
<script  src="{{ asset('GradientAble/files/bower_components/pnotify/js/pnotify.nonblock.js') }}"></script>
<script  src="{{ asset('GradientAble/files/assets/pages/pnotify/notify.js') }}"></script>
<!-- sweet alert js -->
<script  src="{{ asset('GradientAble/files/bower_components/sweetalert/js/sweetalert.min.js') }}"></script>
<!-- modalEffects js nifty modal window effects -->
<script src="{{ asset('GradientAble/files/assets/js/classie.js') }}"></script>
<script  src="{{ asset('GradientAble/files/assets/js/modalEffects.js') }}"></script>
<!-- Bootstrap date-time-picker js -->
<script src="{{ asset('GradientAble/files/assets/pages/advance-elements/moment-with-locales.min.js') }}"></script>
<script src="{{ asset('GradientAble/files/bower_components/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ asset('GradientAble/files/assets/pages/advance-elements/bootstrap-datetimepicker.min.js') }}"></script>
<!-- Date-range picker js -->
<script src="{{ asset('GradientAble/files/bower_components/bootstrap-daterangepicker/js/daterangepicker.js') }}"></script>
<!-- Date-dropper js -->
<script src="{{ asset('GradientAble/files/bower_components/datedropper/js/datedropper.min.js') }}"></script>
<!-- Color picker js -->
<script src="{{ asset('GradientAble/files/bower_components/spectrum/js/spectrum.js') }}"></script>
<script src="{{ asset('GradientAble/files/bower_components/jscolor/js/jscolor.js') }}"></script>
<!-- Mini-color js -->
<script src="{{ asset('GradientAble/files/bower_components/jquery-minicolors/js/jquery.minicolors.min.js') }}"></script>
<!-- Parsley js -->
<!-- validator -->
<script src="{{ asset('GradientAble/files/assets/pages/parsleyjs/parsley.min.js') }}"></script>
@if (Session::get('lang') == 'es' || Session::get('lang') == null)
<script src="{{ asset('GradientAble/files/assets/pages/parsleyjs/i18n/es.js') }}"></script>   
@endif
<!-- Select 2 js -->
<script  src="{{ asset('GradientAble/files/bower_components/select2/js/select2.full.min.js') }}"></script>
<!-- Editable-table js -->
<!-- <script  src="{{ asset('js/jquery.tabledit.js') }}"></script> -->
@stack('scripts')
<!-- Custom js -->
<script src="{{ asset('GradientAble/files/assets/js/pcoded.min.js') }}"></script>
<script src="{{ asset('GradientAble/files/assets/js/vertical/menu/menu-compact.js') }}"></script>
<script src="{{ asset('GradientAble/files/assets/js/jquery.mCustomScrollbar.concat.min.js') }}"></script>
<script  src="{{ asset('GradientAble/files/assets/js/script.js') }}"></script>

prueba/resources/views/admin/shared/sidebar.blade.php
<div class="pcoded-navigation-label" style="color: black;">Menú</div>
    <ul class="pcoded-item pcoded-left-item">
        <li class="pcoded-hasmenu">
            <a>
                <span class="pcoded-micon">
                    <i class="ti-shield"></i>
                </span>
                <span class="pcoded-mtext">Seguridad</span>
            </a>
            <ul class="pcoded-submenu">
                <li>
                    <a href="{{ route('persons.index') }}">
                        <span class="pcoded-micon">
                            <i class="ti-user"></i> 
                        </span>
                        <span class="pcoded-mtext"> Personas</span>
                    </a>
                </li>
            </ul>
        </li>         
        <li class="nohasmenu">
            <a href="{{ route('areas.index') }}">
                <span class="pcoded-micon">
                    <i class="ti-layout-media-right-alt"></i>
                </span>
                <span class="pcoded-mtext"> Áreas</span>
            </a>
        </li> 
        <li class="nohasmenu">
            <a href="{{ route('email.index') }}">
                <span class="pcoded-micon">
                    <i class="ti-email"></i>
                </span>
                <span class="pcoded-mtext"> Email</span>
            </a>
        </li> 
    </ul>
</div>